# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 22:54
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170805_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='posts')),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('summary', models.TextField(max_length=1000)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('meta_description', models.TextField(max_length=155)),
                ('opengraph', models.ImageField(blank=True, null=True, upload_to='opengraph')),
                ('twitter_card', models.ImageField(blank=True, null=True, upload_to='twitter_card')),
                ('seen', models.BigIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
                ('phrase', models.ManyToManyField(blank=True, null=True, to='main.Phrase')),
            ],
        ),
    ]
