# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='phrase',
            new_name='phrases',
        ),
    ]
