# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170806_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
