# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=False, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='seen',
            field=models.IntegerField(default=0),
        ),
    ]
