# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170806_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(default=False, max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='title_page',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
